---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
  register: result
  retries: 5
  until: result is success

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-client
    - mariadb-server
    - python3-mysqldb
  register: result
  retries: 5
  until: result is success
  notify: Start MariaDB service

- meta: flush_handlers
