---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
  retries: 5
  delay: 5

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-client
    - mariadb-server
    - python3-mysqldb
  notify: Start MariaDB service
  retries: 5
  delay: 5

- meta: flush_handlers
