---
- name: Set root password
  mysql_user:
    login_user: root
    user: "root"
    password: "{{ root_psswd }}"
    host: "localhost"
  ignore_errors: true
  register: result

- name: Set root password if previous task failed
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: "root"
    password: "{{ root_psswd }}"
    host: "localhost"
  when: result.failed

- name: Deletes anonymous server user
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: ""
    host_all: yes
    state: absent

- name: Secures the MYSQL root user for IPv6 localhost
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: "root"
    password: "{{ root_psswd }}"
    host: "::1"

- name: Secures the MYSQL root user for IPv4 localhost
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: "root"
    password: "{{ root_psswd }}"
    host: "127.0.0.1"

- name: Secures the MYSQL root user for localhost domain
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: "root"
    password: "{{ root_psswd }}"
    host: "localhost"

- name: Secures the MYSQL root user for server_hostname domain
  mysql_user:
    login_user: root
    login_password: "{{ root_psswd }}"
    user: "root" 
    password: "{{ root_psswd }}"
    host: "{{ ansible_fqdn }}"

- name: Removes the MYSQL test database
  mysql_db:
    login_user: root
    login_password: "{{ root_psswd }}"
    db: test
    state: absent
  notify: Restart MariaDB service
