---
- name: Delete firewalld if it is install
  dnf:
    name: firewalld
    state: absent

- name: install ufw
  dnf:
    name: ufw
    state: present
  register: result
  retries: 5
  until: result is success
  notify: Start ufw MariaDB

- meta: flush_handlers

- name: Allow ssh service
  ufw:
    rule: allow
    name: ssh
  notify:
    - Enable ufw MariaDB
    - Reload ufw MariaDB

- meta: flush_handlers

- name: Allow MariaDB service
  ufw:
    rule: allow
    port: 3306
    proto: tcp
  notify:
    - Enable ufw MariaDB
    - Reload ufw MariaDB

- meta: flush_handlers
