---
- name: Recargar firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Iniciar ufw
  service:
    name: ufw
    state: started
    enabled: yes

- name: Recargar ufw
  ufw:
    state: reloaded
