---
- name: RedHat - Instalar firewalld
  package:
    name: firewalld
    state: latest

- name: RedHat - Iniciar y habilitar firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: RedHat - Permitir servicios http y https
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify: reload firewalld

- meta: flush_handlers
