---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
  retries: 5
  delay: 5

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
    - wget
    - php
    - php-bcmath
    - php-curl
    - php-imagick
    - php-gd
    - php-mysql
  notify: Start and enable apache2
  retries: 5
  delay: 5
