---
- name: Update and upgrade packages
  yum:
    name: '*'
    state: latest
  retries: 5
  delay: 5

- name: Install dnf
  yum:
    name: dnf
    state: latest
  retries: 5
  delay: 5

- name: Enable EPEL repository
  dnf:
    name: epel-release
    state: latest
  retries: 5
  delay: 5

- name: Install packages
  dnf:
    name: httpd
    state: present
  notify: Start and enable httpd
  retries: 5
  delay: 5
