---
- name: Delete firewalld if it is install
  dnf:
    name: firewalld
    state: absent

- name: install ufw
  dnf:
    name: ufw
    state: present
  retries: 5
  delay: 5
  notify: Start ufw Debian

- name: Allow ssh service
  ufw:
    rule: allow
    name: ssh
  notify:
    - Enable ufw Debian
    - Reload ufw Debian

- name: Allow apache service
  ufw:
    rule: allow
    port: 8080
    proto: tcp
  notify:
    - Enable ufw Debian
    - Reload ufw Debian

- meta: flush_handlers
