---
- name: Start and enable apache2
  systemd:
    name: apache2
    state: started
    enabled: True

- name: Start and enable httpd
  systemd:
    name: httpd
    state: started
    enabled: True

- name: Reload apache2
  systemd:
    name: apache2
    state: reloaded

- name: Reload httpd
  systemd:
    name: httpd
    state: reloaded

- name: Start ufw Debian
  service:
    name: ufw
    state: started

- name: Enable ufw Debian
  ufw:
    state: enabled

- name: Reload ufw Debian
  ufw:
    state: reloaded
