# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#--------------------------------------------------------------------------------------
    config.vm.define "apache" do |apache|
      apache.vm.box = "centos/8"
      apache.vm.hostname = "apache"
      apache.vm.network :private_network, ip: "192.168.10.11"
      apache.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--name", "apache"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
    end

    apache.vm.provision "shell", path: "./slave.sh"
    end
  #--------------------------------------------------------------------------------------
  config.vm.define "mariadb" do |mariadb|
    mariadb.vm.box = "debian/buster64"
    mariadb.vm.hostname = "mariadb"
    mariadb.vm.network :private_network, ip: "192.168.10.12"
    mariadb.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "mariadb"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
  end

  mariadb.vm.provision "shell", path: "./slave.sh"
  end
  #--------------------------------------------------------------------------------------
end