---
- name: Generate broadcast websocket secret
  set_fact:
    broadcast_websocket_secret: "{{ lookup('password', '/dev/null length=128') }}"
    run_once: true
    no_log: true

- name: Generate secret key
  set_fact:
    secret_key: "{{ lookup('password', '/dev/null length=30') }}"
    run_once: true
    no_log: true

- name: Create docker_compose directory
  file:
    path: "~/.awx/awxcompose"
    state: directory

- name: Create Redis socket directory
  file:
    path: "~/.awx/awxcompose/redis_socket"
    state: directory
    mode: 0777

- name: Create Docker Compose Configuration
  copy:
    src: "{{ item.file }}"
    dest: "~/.awx/awxcompose/{{ item.file }}"
    mode: "{{ item.mode }}"
  loop:
    - file: environment.sh
      mode: "0600"
    - file: credentials.py
      mode: "0600"
    - file: docker-compose.yml
      mode: "0600"
    - file: nginx.conf
      mode: "0600"
    - file: redis.conf
      mode: "0664"
    - file: SECRET_KEY
      mode: "0600"

- name: Modify credentials
  lineinfile:
    path: "~/.awx/awxcompose/credentials.py"
    regexp: BROADCAST_WEBSOCKET_SECRET =
    line: BROADCAST_WEBSOCKET_SECRET = "{{ broadcast_websocket_secret | b64encode }}"
    state: present

- name: Modify SECRET_KEY file
  lineinfile:
    path: "~/.awx/awxcompose/SECRET_KEY"
    line: "{{ secret_key }}"
    state: present
