---
- name: Run migrations in task container
  shell: docker-compose run --rm --service-ports task awx-manage migrate --no-input
  args:
    chdir: "~/.awx/awxcompose"

- name: Start the containers
  docker_compose:
    project_src: "~/.awx/awxcompose"
    restarted: true

- name: Update CA trust in awx_web container
  command: docker exec awx_web '/usr/bin/update-ca-trust'

- name: Update CA trust in awx_task container
  command: docker exec awx_task '/usr/bin/update-ca-trust'

- name: Wait for next task
  wait_for:
    timeout: 10

- name: Start the containers
  docker_compose:
    project_src: "~/.awx/awxcompose"
    restarted: true

- name: Wait for next task
  wait_for:
    timeout: 10

- name: Create Preload data
  command: docker exec awx_task bash -c "/usr/bin/awx-manage create_preload_data"
