---
- name: Find backup files
  find:
    path: "{{ backup_dir }}"
  register: found_files

- name: Find latest backup
  set_fact:
    backup_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

- name: Get file path
  set_fact:
    backup_file: "{{ backup_file.path }}"
