---
- include_tasks: mount_nfs.yml

- include_tasks: find_latest_backup.yml
  when: latest_backup is defined and latest_backup == "yes"

- include_tasks: db_restore.yml

- include_tasks: unmount_nfs.yml
