---
- name: Create database
  mysql_db:
    login_user: root
    login_password: "{{ root_passwd }}"
    db: nextcloud
    state: present
  delegate_to: "{{ mysql_server }}"

- name: Create user
  mysql_user:
    login_user: root
    login_password: "{{ root_passwd }}"
    user: "{{ new_db_user }}"
    host: "{{ new_db_user_host }}"
    password: "{{ new_db_user_passwd }}"
    priv: 'nextcloud.*:ALL'
    state: present
  delegate_to: "{{ mysql_server }}"
